//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PankiFoodWebForms {
	
	
	public partial class ActualizarAlimento {
		
		protected System.Web.UI.HtmlControls.HtmlForm form2;
		
		protected System.Web.UI.WebControls.Label lblId;
		
		protected System.Web.UI.WebControls.TextBox txtId;
		
		protected System.Web.UI.WebControls.Label lblNombreAct;
		
		protected System.Web.UI.WebControls.TextBox txtNombreAct;
		
		protected System.Web.UI.WebControls.Label lblDescripcionAct;
		
		protected System.Web.UI.WebControls.TextBox txtDescripcionAct;
		
		protected System.Web.UI.WebControls.Label lblPrecioAct;
		
		protected System.Web.UI.WebControls.TextBox txtPrecioAct;
		
		protected System.Web.UI.WebControls.Button btnActualizar;
	}
}
