//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PankiFoodWebForms {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label lblNombre;
		
		protected System.Web.UI.WebControls.TextBox txtNombre;
		
		protected System.Web.UI.WebControls.Label lblDescripcion;
		
		protected System.Web.UI.WebControls.TextBox txtDescripcion;
		
		protected System.Web.UI.WebControls.Label lblPrecio;
		
		protected System.Web.UI.WebControls.TextBox txtPrecio;
		
		protected System.Web.UI.WebControls.Button button1;
	}
}
