//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PankiFoodWebForms.PankiFoodServices {
    using System.Xml.Serialization;
    using System.Diagnostics;
    using System.Web.Services;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="webconecctSoap", Namespace="http://tempuri.org/")]
    public partial class webconecct : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PruebaConexionOperationCompleted;
        
        private System.Threading.SendOrPostCallback Read_telefonosOperationCompleted;
        
        private System.Threading.SendOrPostCallback Insertar_TelefonoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Actualizar_TelefonoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Eliminar_TelefonoOperationCompleted;
        
        /// <remarks/>
        public webconecct() {
            this.Url = "http://localhost:8081/webconecct.asmx";
        }
        
        public webconecct(string url) {
            this.Url = url;
        }
        
        /// <remarks/>
        public event PruebaConexionCompletedEventHandler PruebaConexionCompleted;
        
        /// <remarks/>
        public event Read_telefonosCompletedEventHandler Read_telefonosCompleted;
        
        /// <remarks/>
        public event Insertar_TelefonoCompletedEventHandler Insertar_TelefonoCompleted;
        
        /// <remarks/>
        public event Actualizar_TelefonoCompletedEventHandler Actualizar_TelefonoCompleted;
        
        /// <remarks/>
        public event Eliminar_TelefonoCompletedEventHandler Eliminar_TelefonoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PruebaConexion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PruebaConexion() {
            object[] results = this.Invoke("PruebaConexion", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PruebaConexionAsync() {
            this.PruebaConexionAsync(null);
        }
        
        /// <remarks/>
        public void PruebaConexionAsync(object userState) {
            if ((this.PruebaConexionOperationCompleted == null)) {
                this.PruebaConexionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPruebaConexionOperationCompleted);
            }
            this.InvokeAsync("PruebaConexion", new object[0], this.PruebaConexionOperationCompleted, userState);
        }
        
        private void OnPruebaConexionOperationCompleted(object arg) {
            if ((this.PruebaConexionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PruebaConexionCompleted(this, new PruebaConexionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Read_telefonos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Read_telefonos() {
            object[] results = this.Invoke("Read_telefonos", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Read_telefonosAsync() {
            this.Read_telefonosAsync(null);
        }
        
        /// <remarks/>
        public void Read_telefonosAsync(object userState) {
            if ((this.Read_telefonosOperationCompleted == null)) {
                this.Read_telefonosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRead_telefonosOperationCompleted);
            }
            this.InvokeAsync("Read_telefonos", new object[0], this.Read_telefonosOperationCompleted, userState);
        }
        
        private void OnRead_telefonosOperationCompleted(object arg) {
            if ((this.Read_telefonosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Read_telefonosCompleted(this, new Read_telefonosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Insertar_Telefono", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Insertar_Telefono(string telefono) {
            object[] results = this.Invoke("Insertar_Telefono", new object[] {
                        telefono});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Insertar_TelefonoAsync(string telefono) {
            this.Insertar_TelefonoAsync(telefono, null);
        }
        
        /// <remarks/>
        public void Insertar_TelefonoAsync(string telefono, object userState) {
            if ((this.Insertar_TelefonoOperationCompleted == null)) {
                this.Insertar_TelefonoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertar_TelefonoOperationCompleted);
            }
            this.InvokeAsync("Insertar_Telefono", new object[] {
                        telefono}, this.Insertar_TelefonoOperationCompleted, userState);
        }
        
        private void OnInsertar_TelefonoOperationCompleted(object arg) {
            if ((this.Insertar_TelefonoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Insertar_TelefonoCompleted(this, new Insertar_TelefonoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Actualizar_Telefono", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Actualizar_Telefono(int id, string telefono) {
            object[] results = this.Invoke("Actualizar_Telefono", new object[] {
                        id,
                        telefono});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Actualizar_TelefonoAsync(int id, string telefono) {
            this.Actualizar_TelefonoAsync(id, telefono, null);
        }
        
        /// <remarks/>
        public void Actualizar_TelefonoAsync(int id, string telefono, object userState) {
            if ((this.Actualizar_TelefonoOperationCompleted == null)) {
                this.Actualizar_TelefonoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizar_TelefonoOperationCompleted);
            }
            this.InvokeAsync("Actualizar_Telefono", new object[] {
                        id,
                        telefono}, this.Actualizar_TelefonoOperationCompleted, userState);
        }
        
        private void OnActualizar_TelefonoOperationCompleted(object arg) {
            if ((this.Actualizar_TelefonoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Actualizar_TelefonoCompleted(this, new Actualizar_TelefonoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Eliminar_Telefono", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Eliminar_Telefono(int id) {
            object[] results = this.Invoke("Eliminar_Telefono", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Eliminar_TelefonoAsync(int id) {
            this.Eliminar_TelefonoAsync(id, null);
        }
        
        /// <remarks/>
        public void Eliminar_TelefonoAsync(int id, object userState) {
            if ((this.Eliminar_TelefonoOperationCompleted == null)) {
                this.Eliminar_TelefonoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminar_TelefonoOperationCompleted);
            }
            this.InvokeAsync("Eliminar_Telefono", new object[] {
                        id}, this.Eliminar_TelefonoOperationCompleted, userState);
        }
        
        private void OnEliminar_TelefonoOperationCompleted(object arg) {
            if ((this.Eliminar_TelefonoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Eliminar_TelefonoCompleted(this, new Eliminar_TelefonoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    public delegate void PruebaConexionCompletedEventHandler(object sender, PruebaConexionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PruebaConexionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PruebaConexionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    public delegate void Read_telefonosCompletedEventHandler(object sender, Read_telefonosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Read_telefonosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Read_telefonosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    public delegate void Insertar_TelefonoCompletedEventHandler(object sender, Insertar_TelefonoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Insertar_TelefonoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Insertar_TelefonoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    public delegate void Actualizar_TelefonoCompletedEventHandler(object sender, Actualizar_TelefonoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Actualizar_TelefonoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Actualizar_TelefonoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    public delegate void Eliminar_TelefonoCompletedEventHandler(object sender, Eliminar_TelefonoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("MonoDevelop", "2.6.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Eliminar_TelefonoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Eliminar_TelefonoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
